<a href="https://colab.research.google.com/github/342olive/scraped-data/blob/main/from_scratch_implementations/softmax_activation_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import math
import numpy as np
E= math.e
nnfs.init()

layer_outputs= [[4.8, 1.21, 2.385],
                [8.9, -1.81, 0.2],
                [1.41, 1.051, 0.026]]


exp_values= np.exp(layer_outputs)# result is an array, not a list

norm_base= sum(exp_values)  #sum() function is the most efficient way to calculate the sum of all elements in a list
norm_values=[]

for value in exp_values:
  norm_values.append(value/norm_base) # the division operation in this code means that norm_base is a scalar value and value is an euler exponentiated value
print(norm_values)
print(sum(norm_values))

[0.8952826639572619, 0.024708306782099374, 0.0800090292606387]
0.9999999999999999


In [ ]:
import math
import numpy as np
E= math.e


layer_outputs= [[4.8, 1.21, 2.385],
                [8.9, -1.81, 0.2],
                [1.41, 1.051, 0.026]]

exp_values= np.exp(layer_outputs)
# print(exp_values)
norm_values= exp_values/(np.sum(layer_outputs, axis= 1, keepdims= True))
print(norm_values)

[[1.44741415e+01 3.99462138e-01 1.29351551e+00]
 [1.00575769e+03 2.24491271e-02 1.67544960e-01]
 [1.64694628e+00 1.15018504e+00 4.12682327e-01]]


In [ ]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data  # See for code: https://gist.github.com/Sentdex/454cb20ec5acf0e76ee8ab8448e6266c




class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases


class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)

class Activation_Softmax:
  def forward(self,inputs):
    exp_values= np.exp(inputs-np.max(inputs, axis= 1,keepdims= True))
    probabilities= exp_values/np.sum(exp_values, axis= 1, keepdims= True)
    self.output= probabilities

X, y = spiral_data(samples=100, classes=3)
layer1 = Layer_Dense(2,5)
activation1 = Activation_ReLU()

layer1.forward(X)

#print(layer1.output)
activation1.forward(layer1.output)
print(activation1.output)